### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by RRethy** [aurae-runtime/ae#34]
`make test` fails currently.

We may also want to bring in a testing library (https://github.com/stretchr/testify).

`OutputFormat` should use the generic test suite

**Comment by voigt** [comment]
Make test is fixed now. I think the main point of this issue is obsolete.

However, maybe we can create another issue discussing (and documenting a decision) about the use of a testing framework. I for one would still like to rely on something like testifies assertions (opposed to writing our own ones).
